FROM mcr.microsoft.com/playwright/python:v1.57.0-jammy 

COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app

CMD ["python", "-m", "app.worker.worker_main"]